### ISSUE TITLE
About 5 windows

### ISSUE THREAD

**Issue by DynamticS** [XuanhaoLiu/MoGE#1]
That's great work, and thank you for sharing the model code.  May I know how the 5 windows are specifically divided in the dataset?

**Comment by XuanhaoLiu** [comment]
Hi,

Thank you for your interest in our paper and for bringing up these issues!

For an EEG dataset $X \in \mathbb{R}^{C\times T}$, where C is the number of channels and T is the total number of time points. We use a sliding window whose length is $t$ to sample $n = \frac{T}{t}$ EEG segments: $X =$ { $x_1, x_2, ..., x_n$ }, where $x_i \in \mathbb{R}^{C\times t}$. The input of MoGE is a stack of continuous 5 EEG segments: $X_{in}$ =  { $x_{i-2}, x_{i-1}, x_i, x_{i+1}, x_{i+2}$ } $\in \mathbb{R} ^ {5\times C\times t}$. Actually, we extract the DE feature, so the input is $X_{in}' \in \mathbb{R} ^ {5\times C\times D}$, where $D$ is the number of frequency band.

The segmentation and feature extraction are also depicted in the model figure, where 5 continuous DE feature compose the input of MoGE.

BTW, since the BIBM24 has not opened yet, I have uploaded the final version of our paper in this repo, you can find more details and motivations referring to our paper.

 If you have any more questions or need further assistance, please feel free to ask.
